### ISSUE TITLE
The plugin doesnt work

### ISSUE THREAD

**Issue by ghost** [DiabolicaTrix/Showcase-Mod#1]
If i put the plugin in my server my server crashes and doesnt start.

**Comment by DiabolicaTrix** [comment]
It is not a plugin, it is a forge mod. Also, I cannot fix it if I have no clue what is causing the crash so if you want a fix, I need the server logs

**Comment by ghost** [comment]
Oh so this mod is not a server side mod that can be used for servers. cause it keeps giving me messages on the server like this = [Netty Epoll Server IO #4/ERROR] [FML]: Network Disconnect: Server Mod rejections:
Showcase Mod: Requires version 1.0 but mod is not found on client.

**Comment by DiabolicaTrix** [comment]
No, you need the mod on both sides because the mod is adding blocks and items, sorry for the misunderstanding.

**Comment by ghost** [comment]
Oh :*(. if it would be just a server side mod it would be a really great
plugin/mod.
